[package]
name = "gmt-lom"
version = "0.1.7"
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope Geometric Linear Optical Transformations"
repository = "https://github.com/rconan/gmt-lom"
documentation = "https://docs.rs/gmt-lom"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]
default-run = "main"
exclude = ["lompy/"]

[dependencies]
bincode = "1.3.3"
nalgebra = "0.30"
serde = { version = "1.0.131", features = ["derive"] }
thiserror = "1.0.30"
crseo = { version = "0.1.0", path = "../crseo", optional = true}
skyangle = "0.1"
anyhow = "1.0.51"
complot = { version = "0.3.1", features = ["png"], optional = true }
arrow = { version = "10.0", optional = true }
parquet = { version = "10.0", optional = true }
structopt = "0.3.26"
welch-sde = { version = "0.1.0",  path = "../welch-sde", optional = true }
serde-pickle = "1.1.0"
csv = "1.1.6"

[features]
apache = ["arrow", "parquet"]
main = ["apache", "complot", "welch-sde"]

[[bin]]
name = "main"
required-features = ["main"]

[[bin]]
name = "makesens"
required-features = ["crseo"]

[package.metadata.docs.rs]
features = ["apache"]
