[package]
name = "gmt-lom"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope Geometric Linear Optical Transformations"
repository = "https://github.com/rconan/gmt-lom"
documentation = "https://docs.rs/gmt-lom"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]
default-run = "main"

[dependencies]
bincode = "1.3.3"
nalgebra = "0.29.0"
serde = { version = "1.0.131", features = ["derive"] }
thiserror = "1.0.30"
skyangle = "0.1.0"
anyhow = "1.0.51"
complot = { version = "0.3.1", features = ["png"], optional = true }
arrow = { version = "6.4.0", optional = true }
parquet = { version = "6.4.0", optional = true }
crseo = { git = "https://github.com/rconan/crseo.git", branch = "main", optional = true }

[features]
apache = ["arrow", "parquet"]

[[bin]]
name = "main"
required-features = ["apache", "complot"]

[[bin]]
name = "makesens"
required-features = ["crseo"]
