[package]
name = "lompy"
version = "0.1.0"
edition = "2021"
exclude = ["lompy/"]

[dependencies]
serde-reflection = "0.3.5"
serde_yaml = "0.8.23"
gmt-lom = {version = "^0.1",  path = "../"}
serde-generate = "0.20.6"
serde = { version = "1.0.136", features = ["derive"] }
